### ISSUE TITLE
Add image.registry option to Nextcloud Cronjob

### ISSUE THREAD

**Issue by christiangonre** [groundhog2k/helm-charts#1183]
Hi! First, thanks for your Nextcloud Helm chart, is awesome!

When I updated to the latest version of the Helm chart I face some error related with the cronjobs.

The deployment is using properly the new format with the image.registry option (https://github.com/groundhog2k/helm-charts/blob/master/charts/nextcloud/templates/deployment.yaml#L94) but the cronjobs are using the old format yet (https://github.com/groundhog2k/helm-charts/blob/master/charts/nextcloud/templates/cronjobs.yaml#L35) . This causes some errors because they aren´t using the same docker image.

Can I upload a PR to fix this or do you want to modify it?

Thanks in advance!

**Comment by groundhog2k** [comment]
Thank you for finding this! 
❤️
