### ISSUE TITLE
This feature doesn't exist

### ISSUE THREAD

**Issue by generalovmaksim** [groundhog2k/helm-charts#1198]
Hi
I could be wrong, however I thing that the password generating feature doesn't exist
https://github.com/groundhog2k/helm-charts/blob/48715bfc150e3d6091e4dc41ad82870bbeed6e71/charts/wordpress/values.yaml#L213

**Comment by groundhog2k** [comment]
Yes, you are right. This feature was removed in the database charts and I forgot to fix the documentation of the chart dependencies.
I will fix that.
Thank you :-)
