### ISSUE TITLE
postgres: permission denied for schema public when using custom user

### ISSUE THREAD

**Issue by giannoug** [groundhog2k/helm-charts#1201]
When specifying `POSTGRES_DB`, `POSTGRES_DB` and `USERDB_PASSWORD` public schema usage is denied. The user can create another schema and use it as usual, but schema `public` is denied to the (correctly) connected users.

These are the env vars defined on the pod:
```
PGDATA : /var/lib/postgresql/data/pg
POSTGRES_DB : myuser
USERDB_PASSWORD : myuser
USERDB_USER : myuser
```

**Comment by groundhog2k** [comment]
Please have a look at the PR. It might be what you had in mind.
