### ISSUE TITLE
Update redis chart for Redis 6.2.10

### ISSUE THREAD

**Issue by tim-hanssen** [groundhog2k/helm-charts#1203]
Hi!

Can you please update chart to support the security fixes in Redis 6.2.10.

**Comment by groundhog2k** [comment]
I really recommend using Redis version 7.0.8 with all the latest security fixes/updates.
Is there any reason why you can't update to this version? (In my experience, it should be fully backward compatible)

Alternative: It's also possible to use actual chart version (0.7.1) and set the image.tag: "6.2.10" in the values.yaml. This will work.

**Comment by groundhog2k** [comment]
I decided to release version 0.4.13 of this chart with support for Redis 6.2.10.
