### ISSUE TITLE
Redis Deployment vs Statefulset

### ISSUE THREAD

**Issue by tim-hanssen** [groundhog2k/helm-charts#1209]
Hey @groundhog2k 

Would you consider support for the Redis chart to be deployed as a Deployment instead of the current StatefulSet?

For our "non-critical" Redis setups where HA mode is disabled the StatefullSet is giving issues when the Node becomes unavailable. Because the StatefulSet remains in "terminating" state until the node comes back up, the instance is not transferred to another node. We don't mind the data loss, since we also switched disk saving off.

Other suggestions are welcome too.

**Comment by groundhog2k** [comment]
I understand the problem related to the StatfulSet behavior and can reproduce it. I will check what I can do here. Maybe I will add another option to the helm charts values file to switch between Deployment and StatefulSet when HA mode is disabled.

**Comment by groundhog2k** [comment]
@tim-hanssen : Please have a look at the PR I uploaded for test. I think this is what you had in mind.

**Comment by tim-hanssen** [comment]
@groundhog2k seems fine! This should work and I guess is also a more safer method for the non-ha. Nice!
