### ISSUE TITLE
Support for adding custom setting to wp-config.php ? 

### ISSUE THREAD

**Issue by MihaiMoldovanu** [groundhog2k/helm-charts#1233]
in official wordpress image there is a setting to add custom directives to wp-config.php called WORDPRESS_CONFIG_EXTRA . It is possible to add support for it  ?

**Comment by groundhog2k** [comment]
@MihaiMoldovanu : Please have a look at the PR https://github.com/groundhog2k/helm-charts/pull/1234 and give me feedback.
