### ISSUE TITLE
Smtp missing environment variable (for enabling it)

### ISSUE THREAD

**Issue by MMGeri** [groundhog2k/helm-charts#1380]
So there is actually a missing environment variable from the `charts/graylog/_helpers.tpl` file, without it the email alerting won't work. 
https://go2docs.graylog.org/5-0/downloading_and_installing_graylog/docker_installation.htm

GRAYLOG_TRANSPORT_EMAIL_ENABLED

**Comment by groundhog2k** [comment]
Thx @MMGeri  -- Updated and merged
