### ISSUE TITLE
How can I choose the version of mariadb?

### ISSUE THREAD

**Issue by VinGarcia** [groundhog2k/helm-charts#1382]
My setup is pretty simple except that I used fluxcd, these are the only values I overrode from the values.yaml:

```
extraEnvSecrets:
- mariadb
fullnameOverride: mariadb
image:
  tag: 10.1.48
```

The problem is that this is causing an error with the startupProbe:

> bash: healthcheck.sh command not found

Which makes sense, as this script is not inside that version of the image.

What would be the recommended way of choosing a different version of mariadb when using this helm chart?

**Comment by groundhog2k** [comment]
According to https://endoflife.date/mariadb i wouldn't recommend using the old version 10.1.x of MariaDB which is already unsupported. But anyway, if you use the latest chart version but want to combine this with an older MariaDB container image which doesn't support the `healthcheck.sh`, then you should disable the default startupProbe, livenessProbe and readinessProbe.

```
startupProbe:
  enabled: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false
```

Instead you can add your own (custom) probes by using:

```
customStartupProbe:
  ...your yaml here...

customLivenessProbe:
  ...your yaml here...

customReadinessProbe:
  ...your yaml here...
```

**Comment by VinGarcia** [comment]
I see thanks, I will try that then. Thanks, I think we can close this issue
