### ISSUE TITLE
Check PodSecurityContext (fsGroup) for certain charts

### ISSUE THREAD

**Issue by groundhog2k** [groundhog2k/helm-charts#171]
Some charts do not have a default fsGroup defined in podSecurityContext.
Check if this can be fixed without compatibility issue on actual deployments.

Folowing charts are affected:
- commento
- mariadb
- rabbitmq
- redis
-

**Comment by nikkoura** [comment]
Using longhorn, these charts do not work without the fsGroup set to the same values than those specified in the container security context.
What kind of deployment would you like to test? Maybe I can help.

**Comment by groundhog2k** [comment]
Ah, thats good to know. These were my first charts and I simply forgot to set fsGroup. I use a plain vanilla Kubernetes Cluster (mixed architecture) with NFS-storage and have no problems. But of course I will change the default setting of fsGroup. First I would like to test if this has any negative impact on already deployed objects that use the actual chart version.

Having more people testing it with other environmens (K8 and also different storage) is always helpful to make these charts perfect.
Thank you!
