### ISSUE TITLE
Question - what is motivation for independent charts?

### ISSUE THREAD

**Issue by AlexEPetrov** [groundhog2k/helm-charts#337]
Hey, I don't know where to ask here, but question - why you decided to create your own charts instead of extending "old" stable charts or even, for example, from bitnami)? Any specific requirements?  Thanks.

**Comment by nikkoura** [comment]
Well, I am not the author of these charts but I do use them and I can tell you why I do: Bitnami charts do not support ARM64 architecture - at least, not yet.

**Comment by groundhog2k** [comment]
Hi,
You will find an answer on my blog post which explains the topic a bit: https://blog.goeri.de/public-helm-charts/

Summarized:
1. Bitnami offically only supports charts which are based on their own Bitnami docker images
2. (For the moment) these bitnami docker images are x86-64 only - so no ARM64 support - but in my opinion ARM64 gets more relavant in the future cloud
3. The bitnami docker images are often modified in some way and the helm charts are based on these modifications, you can't use most of the charts with other docker images (like the original docker images which are provided by various open source projects)
3. More and more original docker images provided by open source projects supporting multi-architecture (x86-64/ARM64) but don't offer the helm charts
4. The last alternative (Stable helm charts repo - https://github.com/helm/charts ) is deprecated and will not be maintained anymore.
5. Many charts I found didn't consider security (running container as non-root, & unprivileged) - a thing that is important to me.

So situation didn't make me happy at all, thats why I started learning from deprecated stable helm chart repo and creating my own charts.
I think best solution would be to integrate most of the charts from the deprecated stable helm chart repo directly in to the open source projects and provide all from a single source (code, container image and chart).

**Comment by AlexEPetrov** [comment]
Great answer, thank you!
