### ISSUE TITLE
Flux helmrelease validation error on postgres chart

### ISSUE THREAD

**Issue by untcha** [groundhog2k/helm-charts#535]
I'm using flux (https://fluxcd.io/) to maintain my helmreleases. When applying the helm chart for postgres there is an validation error:

`Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
                                          line 21: mapping key "selector" already defined at line 20`

Checking the postgres chart my assumption is that in the statefulset.yaml on line 16 and line 17 the double `selector` key is wrong.

**Comment by groundhog2k** [comment]
Thank you! -Nobody realized that little copy&paste bug before. I'll fix it.
