### ISSUE TITLE
gitea chart always sets sqlite3 as DB_TYPE

### ISSUE THREAD

**Issue by untcha** [groundhog2k/helm-charts#581]
I'm using your gitea chart and stumbled upon this behavior:
When I'm using an external Postgres DB, which was explizitly not created with your Postgres dependency in your chart, and then do the configuration in the gitea config section. The DB type is always overwritten by sqlite3.

I think this behavior is because of this last else statement in the `secureconfig.yaml`

` {{- if .Values.postgres.enabled }}
    {{- $_ := set .Values.gitea.config.database "SSL_MODE" "disable" -}}
    {{- $_ := set .Values.gitea.config.database "DB_TYPE" "postgres" -}}
    {{- $_ := set .Values.gitea.config.database "HOST" (include "postgres.servicename" .) -}}
    {{- $_ := set .Values.gitea.config.database "NAME" .Values.postgres.userDatabase.name -}}
    {{- $_ := set .Values.gitea.config.database "USER" .Values.postgres.userDatabase.user -}}
    {{- $_ := set .Values.gitea.config.database "PASSWD" .Values.postgres.userDatabase.password -}}
  {{- else }}
	{{- $_ := set .Values.gitea.config.database "DB_TYPE" "sqlite3" -}}`

I know I could just use the postgres section in your gitea chart. And to be honest I'm using your postgres chart :-) but seperately.

Do you think this could be handled different?

**Comment by groundhog2k** [comment]
Ah yes.. you are right. My other charts (e.g. ghost, nextcloud) support external database configuration as an alternative but the Gitea chart doesn't. I will take a look at it and improve the chart soon. Thank you for your feedback!

**Comment by untcha** [comment]
Thanks a lot for your fast reply and the effort/support!
Maybe you can consider the same external support for redis as well. I'm also using your redis chart and setting e.g. the timezone in the env varables.

Schöne Grüße aus München nach Berlin :-)

**Comment by groundhog2k** [comment]
I added support for externalDatabase and externalCache settings. Internal chart dependencies (mariadb, postgres, redis)  have priority over external settings. When internal chart dependencies are not used (false), the externalDatabase or cache settings can be enabled and configured. When external settings are disabled (unconfigured) and fallbackToSqlLite is false too, all settings can be provided manually in `gitea.config` section. (see also Readme.md for all details)
