### ISSUE TITLE
add support for     s3.config.php:  in nextcloud

### ISSUE THREAD

**Issue by connorv001** [groundhog2k/helm-charts#761]
I used this helm chart to deploy and I want to use s3 as my primary storage. please tell me how to do so

**Comment by groundhog2k** [comment]
This chart uses the original nextcloud docker image which supports setting env. variables for S3 storage (see: https://hub.docker.com/_/nextcloud)
Add these variables to the env: section of your values.yaml for the helm deployment.

Did this help?

**Comment by connorv001** [comment]
> This chart uses the original nextcloud docker image which supports setting env. variables for S3 storage (see: https://hub.docker.com/_/nextcloud) Add these variables to the env: section of your values.yaml for the helm deployment.
> 
> Did this help?

I didn't really understand how to do it, can you explain a little bit mroe, if you dont mind?

**Comment by groundhog2k** [comment]
The page https://hub.docker.com/_/nextcloud describes the following environment variables for S3 storage:
```
OBJECTSTORE_S3_HOST: The hostname of the object storage server
OBJECTSTORE_S3_BUCKET: The name of the bucket that Nextcloud should store the data in
OBJECTSTORE_S3_KEY: AWS style access key
OBJECTSTORE_S3_SECRET: AWS style secret access key
OBJECTSTORE_S3_PORT: The port that the object storage server is being served over
OBJECTSTORE_S3_SSL (default: true): Whether or not SSL/TLS should be used to communicate with object storage server
OBJECTSTORE_S3_REGION: The region that the S3 bucket resides in.
OBJECTSTORE_S3_USEPATH_STYLE (default: false): Not required for AWS S3
```

That works, because the nextcloud docker image will install a s3.config.php by default that looks like this:
```
<?php
if (getenv('OBJECTSTORE_S3_BUCKET')) {
  $use_ssl = getenv('OBJECTSTORE_S3_SSL');
  $use_path = getenv('OBJECTSTORE_S3_USEPATH_STYLE');
  $CONFIG = array(
    'objectstore' => array(
      'class' => '\OC\Files\ObjectStore\S3',
      'arguments' => array(
        'bucket' => getenv('OBJECTSTORE_S3_BUCKET'),
        'key' => getenv('OBJECTSTORE_S3_KEY') ?: '',
        'secret' => getenv('OBJECTSTORE_S3_SECRET') ?: '',
        'region' => getenv('OBJECTSTORE_S3_REGION') ?: '',
        'hostname' => getenv('OBJECTSTORE_S3_HOST') ?: '',
        'port' => getenv('OBJECTSTORE_S3_PORT') ?: '',
        'use_ssl' => (strtolower($use_ssl) === 'false' || $use_ssl == false) ? false : true,
        // required for some non Amazon S3 implementations
        'use_path_style' => $use_path == true && strtolower($use_path) !== 'false'
      )
    )
  );
}
```

When deploying nextcloud using the helm chart with your own values.yaml configuration you can use the `env:` section to set the S3 environment variables:
```
env:
   - name: OBJECTSTORE_S3_HOST
     value: "..."
   - name: OBJECTSTORE_S3_BUCKET
     value: "..."
   ...
```

That should work to connect AWS S3 as primary storage.

Hint: I will update the helm chart soon to support adding customized *.config.php files during deployment. :-)

**Comment by groundhog2k** [comment]
The releases chart version 0.10.0 of the Nextcloud helm chart supports adding custom *.config.php files. This is an alternative to setting the OBJECTSTORE_S3_* environment variables. (see https://github.com/groundhog2k/helm-charts/blob/master/charts/nextcloud/README.md)

**Comment by groundhog2k** [comment]
Closed due to no feedback.
