### ISSUE TITLE
Specifying passwords by reference

### ISSUE THREAD

**Issue by ellakk** [groundhog2k/helm-charts#835]
Hello,
I'm an avid user of your charts, but I've run into a problem after we started to use ArgoCD to deploy our helmcharts. We use SopsSecret operator to deploy our secrets, since we do not want to store them under version control for security reasons. Your database charts does not support setting passwords by referring to secrets (at least not postgres/maria), and we can't use the random generated passwords functionality in your charts since ArgoCD will overwrite them with a new password on each upgrade. Must charts we use has this functionality built in, and it would be nice if your did to.

**Comment by groundhog2k** [comment]
Alright, I will take a look at it

**Comment by groundhog2k** [comment]
I found a solution for MariaDB chart and actually test it and will adapt that for postgres and maybe also mongodb chart.

**Comment by ellakk** [comment]
Ok, cool. Thanks a lot!
